image:
  repository: odoo
  tag: "19"
  pullPolicy: IfNotPresent

postgresql:
  host: "10.0.100.20"
  port: "5432"
  user: "root"
  password: "VidUxZ6MEKfR04c97GcLz3P2uVS3ZNQYIqH1"
  database: "odoo"

persistence:
  enabled: true
  mountPath: /var/lib/odoo
  storageClass: nfs-client

  # üì¶ Tama√±os por tipo de volumen
  dataSize: 5Gi
  addonsSize: 2Gi
  filestoreSize: 5Gi
  nfsSize: 5Gi

  # üî∏ Si usas un PVC existente (por ejemplo restaurado), especif√≠calo aqu√≠.
  # Si se deja vac√≠o, el chart crea uno nuevo din√°micamente: <release>-data-pvc
  existingClaim: ""

extraAddonsPath: /mnt/extra-addons

service:
  type: ClusterIP
  port: 8069           # Cambia si tienes otro Odoo en el cluster

domain: "odoo.cuidatassistencia.cat"

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    certManagerIssuer: letsencrypt-prod

extraArgs:
  - "-i"
  - "base"
  - "--without-demo=all"